"""Add home to PlayerGame

Revision ID: 3d99d8e02862
Revises: 0c7c0ba3b794
Create Date: 2023-10-31 03:39:24.175341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d99d8e02862'
down_revision = '0c7c0ba3b794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_game', sa.Column('home', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_game', 'home')
    # ### end Alembic commands ###
