"""Added Position and Team columns

Revision ID: 4fa247460213
Revises: 6d08f7cf02b6
Create Date: 2023-11-10 18:37:36.872000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa247460213'
down_revision = '6d08f7cf02b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'position')
    # ### end Alembic commands ###
