"""Add date to FinalBet repr

Revision ID: 5273d2c177bc
Revises: 6fc3962d02d1
Create Date: 2024-02-05 08:19:08.882476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5273d2c177bc'
down_revision = '6fc3962d02d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
