"""empty message

Revision ID: 6d08f7cf02b6
Revises: 3d99d8e02862
Create Date: 2023-11-02 09:49:04.081210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d08f7cf02b6'
down_revision = '3d99d8e02862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_game', sa.Column('minutes', sa.Integer(), nullable=True))
    op.add_column('player_game', sa.Column('tsp', sa.Float(), nullable=True))
    op.add_column('player_game', sa.Column('eft', sa.Float(), nullable=True))
    op.add_column('player_game', sa.Column('ORtg', sa.Integer(), nullable=True))
    op.add_column('player_game', sa.Column('DRTg', sa.Integer(), nullable=True))
    op.add_column('player_game', sa.Column('BPM', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_game', 'BPM')
    op.drop_column('player_game', 'DRTg')
    op.drop_column('player_game', 'ORtg')
    op.drop_column('player_game', 'eft')
    op.drop_column('player_game', 'tsp')
    op.drop_column('player_game', 'minutes')
    # ### end Alembic commands ###
